import type { Media, User } from '@/payload-types'
import { RequiredDataFromCollectionSlug } from 'payload'

export type PostArgs = {
  heroImage: Media
  blockImage: Media
  author: User
}

export const post3: (args: PostArgs) => RequiredDataFromCollectionSlug<'posts'> = ({
  heroImage,
  blockImage,
  author,
}) => {
  return {
    slug: 'whats-actually-burning',
    _status: 'published',
    authors: [author],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "A candle isn't just ambiance. It's chemistry, botany, and a little bit of ritual — all in one slow burn.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Most people light a candle and walk away. Which is exactly the point — it's effortless comfort. But there's more happening in that jar than a flickering flame. From the moment you strike a match, your botanical candle is doing something surprisingly sophisticated. Here's what's actually going on.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "The Wax Isn't Just Filler",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Wax is the fuel. It feeds the flame and carries scent into the air. But not all wax behaves the same way. Paraffin — the standard in mass-produced candles — is a petroleum byproduct. It burns hotter and faster, and releases trace amounts of soot and benzene into your space. Not what you want from a wellness ritual.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Candera uses coconut-soy wax — and the difference shows up in three ways:',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'list',
            children: [
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Cooler burn temperature',
                    version: 1,
                  },
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: " — extends your candle's life by 25–50% compared to paraffin",
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                value: 1,
                version: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Clean combustion',
                    version: 1,
                  },
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' — virtually no soot, no petrochemicals',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                value: 2,
                version: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Better scent throw',
                    version: 1,
                  },
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' — natural waxes hold and release fragrance more evenly as the melt pool forms',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                value: 3,
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            listType: 'bullet',
            start: 1,
            tag: 'ul',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "The wax isn't incidental. It's the foundation of the entire experience.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'The Wick Controls Everything',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "A wick that's too thick burns too hot — you get tunneling, uneven melt pools, and a candle that consumes itself unevenly. Too thin and the flame drowns in its own wax. Cotton wicks, when properly sized for the vessel diameter, create a self-trimming flame that stays stable, burns cleaner, and draws wax evenly across the surface.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 1,
                mode: 'normal',
                style: '',
                text: 'The first burn rule:',
                version: 1,
              },
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' Let your candle burn until the wax pool reaches the edge of the jar — this sets the "memory" of the candle. Skip this step and you\'ll get tunneling, a narrow hole straight down the center that leaves wasted wax on the sides permanently. One burn. Full pool. Every burn after that takes care of itself.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: '',
              blockType: 'mediaBlock',
              media: blockImage.id,
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'What Botanicals Actually Do',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Dried flowers and herbs in candles aren't decoration — though they are beautiful. They're a deliberate choice about what your space smells like as the wax melts, and what you're surrounding yourself with as you breathe. Candera's botanical ingredients are chosen for what they release during a burn:",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'list',
            children: [
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Lavender',
                    version: 1,
                  },
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: " — linalool and linalyl acetate, the compounds responsible for lavender's documented calming effect on the nervous system. Not a myth. Studied extensively in aromatherapy research.",
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                value: 1,
                version: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Chamomile',
                    version: 1,
                  },
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' — gentle, apple-adjacent scent with anti-inflammatory compounds that disperse softly into ambient air',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                value: 2,
                version: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Rose petals',
                    version: 1,
                  },
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' — complex floral top notes that fade gracefully, leaving a clean warmth rather than heavy sweetness',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                value: 3,
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            listType: 'bullet',
            start: 1,
            tag: 'ul',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "The key word is release. Botanicals behave differently in heat than they do cold. What you smell when you open the jar is not exactly what you'll smell after the candle has been burning for twenty minutes. The warmth develops the scent — and that's when it becomes something else entirely.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Cold Throw vs. Hot Throw',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 1,
                mode: 'normal',
                style: '',
                text: 'Cold throw',
                version: 1,
              },
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' is the scent you smell from an unlit candle — the first impression in the store, the one that sells you on it. ',
                version: 1,
              },
              {
                type: 'text',
                detail: 0,
                format: 1,
                mode: 'normal',
                style: '',
                text: 'Hot throw',
                version: 1,
              },
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' is what actually fills your room — more complex, more layered, and in a well-made botanical candle, more true to the plant itself.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Synthetic fragrances are engineered for strong cold throw. Natural botanical blends often have a subtler cold throw but a richer, more nuanced hot throw. If you've ever bought a strongly-scented candle that seemed to disappear once lit, this is likely why. Candera candles are formulated for hot throw. Light one, give it fifteen minutes, and then take a breath.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'The Flame Is Alive',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'A candle flame is a self-sustaining chemical reaction happening in four distinct zones, all at once:',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'list',
            children: [
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'The blue base',
                    version: 1,
                  },
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' — incomplete combustion where oxygen is limited and temperature is highest',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                value: 1,
                version: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'The dark inner cone',
                    version: 1,
                  },
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' — unburned vaporized wax traveling upward',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                value: 2,
                version: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'The luminous zone',
                    version: 1,
                  },
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' — the bright glow where carbon particles heat to incandescence',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                value: 3,
                version: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'The outer veil',
                    version: 1,
                  },
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' — where combustion completes and CO₂ and water vapor release',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                value: 4,
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            listType: 'bullet',
            start: 1,
            tag: 'ul',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "The teardrop shape isn't accidental either. Gravity and convection pull cooler air in at the base and push hot gases up and outward, maintaining the shape continuously. In microgravity — like on the International Space Station — candle flames form perfect spheres. You're watching physics every time you light a candle. It's just quiet enough that it feels like peace.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Burn with Intention',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Understanding your candle doesn't make it less magical. It makes the ritual more intentional. You're not just burning wax — you're releasing botanical compounds into the air you breathe, creating a sensory environment your nervous system responds to, and giving yourself a slow, deliberate pause in your day.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "That's what Candera is built for.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    heroImage: heroImage.id,
    meta: {
      description:
        'From wax chemistry to why your first burn matters — a real look at the science inside every Candera botanical candle.',
      image: heroImage.id,
      title: "What's Actually Burning: The Science Behind Your Botanical Candle | Candera",
    },
    relatedPosts: [],
    title: "What's Actually Burning: The Science Behind Your Botanical Candle",
  }
}
