import { RequiredDataFromCollectionSlug } from 'payload'
import type { PostArgs } from './post-1'

export const post5: (args: PostArgs) => RequiredDataFromCollectionSlug<'posts'> = ({
  heroImage,
  blockImage,
  author,
}) => {
  return {
    slug: 'five-candle-mistakes',
    _status: 'published',
    authors: [author],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Your candle is trying to last. Here's what's getting in the way.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "A well-made botanical candle should give you 50 hours of burn time. Most people get significantly less — not because the candle is poor quality, but because of five very fixable habits. Here's what they are and how to correct them.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '1. You Skipped the First Burn',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Wax has memory. The first time you light a candle, it will only melt as wide as it did that first time — every burn after that follows the same pattern. If you blew it out after twenty minutes, you've trained your candle to tunnel: a narrow shaft straight down the middle, leaving wax permanently on the sides.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'The fix is simple, and it only needs to happen once: on your first burn, let the candle go until the melt pool reaches the full edge of the jar. For most Candera vessels, that takes two to three hours. After that, every burn is a full, even pool. The wax memory is set.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "2. You're Burning in a Draft",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Air movement — from an open window, a ceiling fan, a heating vent — disrupts the combustion cycle. The flame flickers and leans, burning unevenly and consuming more wax on the windward side. You'll see it as black marks on the jar: soot left by an unstable flame that can't complete its burn cleanly.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Move the candle away from direct airflow. The flame should burn upright and still, with only a gentle, natural movement. If it's flickering consistently, it's not in the right spot.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: '',
              blockType: 'mediaBlock',
              media: blockImage.id,
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "3. You Haven't Been Trimming the Wick",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "After each burn, the wick tip forms a small carbon mushroom — the residue of combustion. If you don't remove it before the next burn, that mushroom makes the flame burn larger and hotter than it should. More heat means faster wax consumption, more soot, and a shorter candle life.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Trim to about ¼ inch before each burn — always when the wax is cool and solid. A wick trimmer makes this easy, but small scissors work fine. The flame should sit calm and about an inch tall. If it's larger than that, the wick needs trimming.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '4. You Burn for Less Than an Hour at a Time',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Short burns don't give the wax pool time to fully form. You get partial melt, uneven burn patterns, and over time, the same tunneling effect as skipping the first burn. The candle never gets the chance to perform the way it was designed.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Aim for a minimum of one hour per burn, and no more than four hours at a stretch — after four hours, the wax gets too warm, the scent throw weakens, and the wick can become too long from continuous burning. Think of it as an intentional window: light the candle when you're settling in, and let it burn through the ritual.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '5. You Store Your Candles in Direct Light',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Natural wax and botanical fragrance oils are sensitive to UV light and heat. A candle sitting in a sunny window will slowly discolor, lose scent strength, and in warm climates, can begin to soften at the surface — affecting how evenly it burns when you finally light it.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Store unlit candles away from direct sunlight and heat sources — a shelf, a drawer, a cool surface. Replace the lid between burns to protect the wax surface and preserve the scent. A Candera candle kept properly will smell just as strong on its fiftieth hour as it did on its first.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'The Short Version',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'list',
            children: [
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'First burn: full melt pool, edge to edge',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                value: 1,
                version: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Keep away from drafts and moving air',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                value: 2,
                version: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Trim the wick to ¼ inch before every burn',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                value: 3,
                version: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Burn for at least one hour, no more than four',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                value: 4,
                version: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Store out of direct sunlight with the lid on',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                value: 5,
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            listType: 'bullet',
            start: 1,
            tag: 'ul',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "None of this is complicated. It's just a small amount of attention paid to something made to last — and to make your space feel like something worth returning to.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    heroImage: heroImage.id,
    meta: {
      description:
        'Five common candle habits that cut your burn time short — and exactly how to fix each one.',
      image: heroImage.id,
      title: 'Five Candle Mistakes That Are Costing You Hours of Burn Time | Candera',
    },
    relatedPosts: [],
    title: 'Five Candle Mistakes That Are Costing You Hours of Burn Time',
  }
}
