import { RequiredDataFromCollectionSlug } from 'payload'
import type { PostArgs } from './post-3'

export const post4: (args: PostArgs) => RequiredDataFromCollectionSlug<'posts'> = ({
  heroImage,
  blockImage,
  author,
}) => {
  return {
    slug: 'botanicals-behind-the-burn',
    _status: 'published',
    authors: [author],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Not decoration. Not marketing. The botanicals in your Candera candle are doing something.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Every Candera candle is built around a botanical — a dried flower, herb, or bloom chosen for what it brings to the burn. Not for how it photographs, though that matters too. For what it releases as the wax melts, what it does to the air in your space, and what that does to you. Here's a closer look at the botanicals behind the burn.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Why Plant Matter in a Candle?',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Scent is the only sense with a direct pathway to the limbic system — the part of the brain that governs memory, emotion, and the body's stress response. This is why a familiar smell can stop you mid-step. It's not nostalgia being sentimental. It's biology being efficient.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'When you burn a botanical candle, scent compounds from the wax blend — and from the botanicals themselves as they warm — move through the air and into your olfactory receptors. Those receptors send signals directly to the amygdala and hippocampus. The result is a measurable physiological shift. Your shoulders drop. Your breathing slows. The room feels different.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Lavender: The Compound You Can Feel',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Lavender's calming reputation isn't folk medicine. It's backed by decades of research into its primary compounds: linalool and linalyl acetate. Linalool has been shown to reduce anxiety markers in clinical settings. Linalyl acetate has a mild sedative effect on the central nervous system. Together they create the quiet that lavender is known for.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "In a candle, lavender behaves differently than in a diffuser or a sachet. The heat from the wax releases the volatile compounds slowly over the duration of the burn, rather than all at once. You're not hit with lavender — you're surrounded by it, gradually, which is closer to how the plant exists in nature.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: '',
              blockType: 'mediaBlock',
              media: blockImage.id,
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Rose: Complexity in Every Note',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Rose is one of the most chemically complex botanicals used in fragrance. A single rose bloom contains hundreds of distinct scent compounds — geraniol, citronellol, nerol, damascenone — each contributing a different facet of what we recognize as "rose." Warm and heady at the start, cleaner and greener as it dries down.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Dried rose petals in a candle release their more delicate volatile compounds first, followed by deeper, earthier base notes as the wax pools. It's a bloom in slow motion — which is exactly why rose works so well in a candle rather than a spray. The progression is the point.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Florals That Layer: Lilac, Pansy, and Hydrangea',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Not all botanicals are fragrance powerhouses on their own. Lilac, pansy, and hydrangea are what perfumers call soft or elusive florals — their scent is real but subtle, and in a candle they serve as middle notes that bridge the gap between the boldness of a top note and the warmth of a base.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Lilac carries a cool, slightly powdery quality — think early spring before anything gets too warm. Pressed pansy is similar: quiet and contemplative, almost literary. Blue hydrangea rounds out the floral family with a fresh, aqueous undertone that keeps heavier florals from becoming overpowering. Together they create the layered complexity that makes a room smell like something, without smelling like anything specific enough to name.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'The Drydown: Where the Scent Lives',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "In perfumery, the drydown is what happens after the top notes evaporate — the deeper, longer-lasting scent that remains. In a candle, this translates to the scent that lingers in the room after you've blown it out. The vetiver in Crimson Noir. The soft musk under Ever After Glow's hydrangeas. The salt air that stays in the air after Seashell Garden cools.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "This is the scent you return home to. The one your space holds long after the candle is out. It's not an accident — it's the most considered part of building a botanical fragrance. The top note introduces. The heart defines. The drydown stays.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    heroImage: heroImage.id,
    meta: {
      description:
        'A closer look at the lavender, rose, lilac, and other botanicals inside Candera candles — what they are, what they do, and why they matter.',
      image: heroImage.id,
      title: 'The Botanicals Behind the Burn | Candera',
    },
    relatedPosts: [],
    title: 'The Botanicals Behind the Burn: What Each Flower Actually Does',
  }
}
