import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload: _payload, req: _req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "folders_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "folders_create" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "folders_update" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "folders_delete" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "pages_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "pages_create" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "pages_update" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "pages_delete" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "posts_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "posts_create" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "posts_update" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "posts_delete" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "products_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "products_create" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "products_update" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "products_delete" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "media_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "media_create" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "media_update" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "media_delete" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "categories_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "categories_create" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "categories_update" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "categories_delete" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "briefs_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "briefs_create" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "briefs_update" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "briefs_delete" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "quizzes_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "quizzes_create" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "quizzes_update" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "quizzes_delete" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "scent_profiles_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "scent_profiles_create" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "scent_profiles_update" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "scent_profiles_delete" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "documentation_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "documentation_create" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "documentation_update" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "documentation_delete" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "how_to_guides_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "how_to_guides_create" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "how_to_guides_update" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "how_to_guides_delete" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "redirects_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "redirects_create" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "redirects_update" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "redirects_delete" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "forms_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "forms_create" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "forms_update" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "forms_delete" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "header_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "header_update" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "footer_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "footer_update" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "site_theme_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "site_theme_update" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "studio_info_find" boolean DEFAULT false;
  ALTER TABLE "payload_mcp_api_keys" ADD COLUMN "studio_info_update" boolean DEFAULT false;`)
}

export async function down({ db, payload: _payload, req: _req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "folders_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "folders_create";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "folders_update";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "folders_delete";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "pages_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "pages_create";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "pages_update";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "pages_delete";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "posts_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "posts_create";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "posts_update";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "posts_delete";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "products_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "products_create";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "products_update";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "products_delete";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "media_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "media_create";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "media_update";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "media_delete";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "categories_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "categories_create";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "categories_update";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "categories_delete";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "briefs_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "briefs_create";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "briefs_update";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "briefs_delete";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "quizzes_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "quizzes_create";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "quizzes_update";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "quizzes_delete";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "scent_profiles_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "scent_profiles_create";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "scent_profiles_update";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "scent_profiles_delete";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "documentation_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "documentation_create";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "documentation_update";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "documentation_delete";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "how_to_guides_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "how_to_guides_create";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "how_to_guides_update";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "how_to_guides_delete";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "redirects_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "redirects_create";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "redirects_update";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "redirects_delete";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "forms_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "forms_create";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "forms_update";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "forms_delete";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "header_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "header_update";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "footer_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "footer_update";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "site_theme_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "site_theme_update";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "studio_info_find";
  ALTER TABLE "payload_mcp_api_keys" DROP COLUMN "studio_info_update";`)
}
